@startuml
'https://plantuml.com/activity-diagram-beta

start

:setup;
:hent spiller data;
if (Er der noget spiller data?) then (Yes)


   else (No)

   :Start dialog;



      endif
        label s
         :lav spillerliste;

      :kør næste runde;


@enduml

