@startuml
'https://plantuml.com/activity-diagram-beta

start

:setup;
:hent spiller data;
if (Er der noget spiller data?) then (Yes)
if (Vil du fortsætte spillet?) then (Yes)

label spc
label spc
label spc
label spc
label spc
label r
:kør næste runde;
stop
  else (No)

       label d
        :Start dialog;

:lav spillerliste;
goto r

  endif
   else (No)
   label tmp
    goto d


      endif



@enduml

