@startuml

participant Main as main
participant Game as game
participant Dice as dice
participant Player as player
participant Board as board
participant Field as field
main -> game : runGameLoop()
loop !quitgame
game -> game : currentPlayer = players[count]
game -> game : throwAndMove()
end

game -> TextUI : displayMessage ("Det er "+currentPlayer.getName+"'s tur")
game -> dice : int result = rollDiceSum()
dice --> game : (8)
game -> player: int newPosition = updatePosition( result )
player --> game : newPosition = (9)
game -> board : Field f = getField( newPosition )
board --> game : (Valbylanggade)
game -> game : landAndAct(f)

@enduml