@startuml
'https://plantuml.com/sequence-diagram

autonumber

Game -> FileIO: readBoardData("fielddata.csv")
FileIO --> Game: String[] data
Game -> Board : new(data)
Board -> Board : createFields(data)
loop data.length
Board -> SubField : Field f = new SubField()
end
SubField -> Field : super.new()

@enduml