@startuml
'https://plantuml.com/class-diagram

class Main

class Customer




class Main{
-ArrayList<Customer> customers
+ static void main(Strin[] args)
+ static void printCustomers()
+ static void testCode()
}
class Customer{
- String name
- int balance
+ Customer(String name, int balance)
+ String toString()
+ void deposit()
}


@enduml