
@startuml
'https://plantuml.com/class-diagram



Main *-- TextUI
Main *-- FileIO
Main *-- Player




class Main{
- static ArrayList<Player> players
- static FileIO io
- static TextUI ui
+ static void main(String[] args)
- static displayPlayers()
}

Player  : - String name
Player  : - int balance
Player  : + Player(String, int)
Player  : + String toString()
Player  : + int deposit()



'todo - TextUI: copy  from drinksmenu (https://github.com/Dat1Cphbusiness/DrinksMenu/blob/main/TextUI.java)
TextUI : + String getInput(String msg)
TextUI : - Scanner scanner


FileIO : - Scanner scanner
FileIO : + ArrayList<Player> readPlayerData(String path)
FileIO : + void savePlayerData(ArrayList<Player> players)

@enduml