@startuml
'https://plantuml.com/sequence-diagram
Participant Main
Participant Game
Participant FileIO
Participant TextUI
Participant Player

Main -> Game: new()
Main -> Game: setup()
Game -> FileIO: new()
Game -> FileIO: readPlayerData()
FileIO --> Game: data

alt data.size()>0
loop (for-each)
Game -> Player: new(name, balance)
end

else
Game -> TextUI: new()

loop (while)
Game -> TextUI: getInput()
Game -> Player: new(input, startAmount)
end

end


'... følg metodekaldene i Game.setup og tegn dem ind som vandrette streger
' returnering af værdier fra en metode *kan* vises med en stiplet pil: <--
' brug alt-else-end til at vise betingelser
' brug loop til at vise gentagelser

Game -> Game : displayPlayers();

@enduml