@startuml
'https://plantuml.com/activity-diagram-beta

start
:start spil;
:hent spil data;
if (Er der data gemt?) then (Yes)

   else (No)
     :Start dialog for at indhente spillernavne;

      endif

:lav spillerobjekter;
stop

@enduml
