@startuml

  actor user as u

  usecase "StartGame" as UC1
  usecase "RegisterPlayers" as UC2
  usecase "ThrowAndMove" as UC3
  usecase "LandAndAct" as UC4
  usecase "EndGame" as UC5

u --> UC1
UC1 --> UC2
UC2 --> UC3
UC3 --> UC4
UC4 --> UC3
UC4 --> UC5
UC5 --> UC2
@enduml
